# Generated by Django 3.2.10 on 2021-12-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('order', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('assigned_user', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateField()),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.status')),
                ('task', models.ManyToManyField(to='projectapp.Task')),
            ],
        ),
    ]
